# Generated by Django 5.2.1 on 2025-06-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='word_level_vtt_file_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
